### ISSUE TITLE
Auth Password seems not to be set by default or won't just be displayed in Adminpanel

### ISSUE THREAD

**Issue by stevenobird** [heidelpay/magento2#10]
When viewing the Heidelpay settings below Stores -> Configuration -> Sales -> Payment Methods, the Authentication password is not displayed at all (not even protected, like ******).

So it might be an issue when changing settings and not setting the password, because the app/log/debug.log shows the following when trying to Checkout an order:

> [PROCESSING_STATUS] => REJECTED_VALIDATION
> [POST_VALIDATION] => NOK
> [PROCESSING_RETURN] => USER.PWD is mandatory but not setted

**Comment by muhkuh2005** [comment]
Can confirm this.
Password is written on the [sandbox documentation](https://dev.heidelpay.com/sandbox-environment/) page though so it is more of an comfort problem.

**Comment by sixer1182** [comment]
Hi @muhkuh2005 
We have this in our backlog, but since there is an easy way around this we didn't come around to investigate. There are much more pressing issues as you know ;-)

**Comment by sixer1182** [comment]
As of today we will disable issue tracking on GitHub.
This is due to most of the issues actually being support issues due to usage problems.
Please send your requests to support@heidelpay.com to receive a Ticket-Number.
We are sorry for any inconvenience this will cause you.
Thanks for understanding,
your HeidelpayDev team.
