### ISSUE TITLE
Feature: Payment Methods available in backend order process

### ISSUE THREAD

**Issue by DavidLambauer** [heidelpay/magento2#15]
After I updated to 17.1.25, I don't have any payment methods available in the backend while I try to create a new order manually. Before the Update, I was able to select at least the credit card information. 
<img width="1836" alt="screenshot at feb 01 10-03-25" src="https://cloud.githubusercontent.com/assets/1841317/22500664/bf5617f6-e865-11e6-96a2-31233273ca91.png">

**Comment by heidelpay** [comment]
Hallo David,

currently your payment method are not usable from backend create order. It was a wrong behavior that they are visible there and the credit card information form was the one from magento itself.

**Comment by DavidLambauer** [comment]
Can we reopen this Issue as a Feature Request please? Several of our projects need this function.

**Comment by heidelpay** [comment]
Sure can you define which payment method would be useful for your projects. 

From my point of view, only direct debit, prepayment  and invoice would be possible.

Credit and Debit Card would not be possible because of the fact that such a transaction is not longer an ecommerce transaction, it is a mail order / telefon order transaction which have a higher risk and need a special contract.

Regards

Jens

**Comment by DavidLambauer** [comment]
Thanks for reopening! 

I like your recommendation, it makes sense to keep it as simple as possible without having trouble with any contracts. 

Greetings David!

**Comment by zolthan** [comment]
We also love to have this feature. Our customer needs to process orders with invoice or direct debit via backend.

**Comment by sixer1182** [comment]
As of today we will disable issue tracking on GitHub.
This is due to most of the issues actually being support issues due to usage problems.
Please send your requests to support@heidelpay.com to receive a Ticket-Number.
We are sorry for any inconvenience this will cause you.
Thanks for understanding,
your HeidelpayDev team.
